name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  create-docker-changes:
    runs-on: ubuntu-latest
    outputs:
      directory: ${{ steps.find-docker-changes.outputs.dir }}
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find Docker Changes
        id: find-docker-changes
        run: |
          # Obter os diretórios que contêm Dockerfile
          find . -type f -name Dockerfile | grep -o '.*/' | uniq | sort | sed 's/\.\///' | rev | sed 's/\///' | rev > docker_dirs.txt
          # Obter os diretórios alterados pelo Git (após a 6ª linha)
          git diff --name-only HEAD~1..HEAD | grep -o '.*/' | uniq | sort | rev | sed 's/\///' | rev > gitshow.txt
          # Extrair os diretórios que aparecem em ambos os arrays
          dir_dif=$(comm -12 docker_dirs.txt gitshow.txt)
          common_dirs=$(printf "${dir_dif[@]}" | jq -R . | jq -s -c . )
          echo "dir=${common_dirs}" >> $GITHUB_OUTPUT

  create-build-matrix:
    needs: create-docker-changes
    runs-on: ubuntu-latest
    if: ${{ !contains(needs.create-docker-changes.outputs.directory, '[]') }}
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.create-docker-changes.outputs.directory) }}
      max-parallel: 4
    outputs:
      build-args-matrix: ${{ steps.find-build-matrix.outputs.build-args-matrix }}
      directory: ${{ matrix.directory }}
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find Build Matrix
        id: find-build-matrix
        env:
          DIR: ${{ matrix.directory }}
        run: |
          cd ${{ env.DIR }}
          build_args_matrix=$(jq -c '.build.args.matrix' config.json)
          echo "build-args-matrix=${build_args_matrix}" >> $GITHUB_OUTPUT

  build-and-push:
    needs: create-build-matrix
    runs-on: ubuntu-latest
    if: ${{ !contains(needs.create-build-matrix.outputs.build-args-matrix, '[]') }}
    strategy:
      matrix:
        build-args-matrix: ${{ fromJSON(needs.create-build-matrix.outputs.build-args-matrix) }}
      max-parallel: 4
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Docker images
        env:
          DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          DIR: ${{ needs.create-build-matrix.outputs.directory }}
          BUILD_ARGS_MATRIX: ${{ toJSON(matrix.build-args-matrix) }}
        run: |
          cd ${{ env.DIR }}
          REPOSITORY_NAME=$(jq -r '.repository.name' config.json)
          TAG=$(echo "${BUILD_ARGS_MATRIX}" | jq -r '.TAG')
          BUILD_ARG=""
          GLOBAL_JSON=$(jq '.build.args.global' config.json)
          for key in $(echo "${GLOBAL_JSON}" | jq -r keys[]); do
            value=$(echo "${GLOBAL_JSON}" | jq -r ".${key}")
            BUILD_ARG="${BUILD_ARG} --build-arg ${key}=${value}"
          done
          for key in $(echo "${BUILD_ARGS_MATRIX}" | jq -r keys[]); do
            value=$(echo "${BUILD_ARGS_MATRIX}" | jq -r ".${key}")
            BUILD_ARG="${BUILD_ARG} --build-arg ${key}=${value}"
          done
          IMAGE_NAME=$(echo "${{ env.DOCKER_REGISTRY_USERNAME }}/${REPOSITORY_NAME}:${TAG}")
          docker build $BUILD_ARG -t $IMAGE_NAME .
          docker push $IMAGE_NAME